# 20719B2 firmware build 211
# patch entries used: 149 out of 256 elf patches, 58%
CY_PATCH_ENTRIES_BASE=149
# additional patch entries in these libraries:
#   2 in ant_lib.a
#   2 in wiced_app_watchdog_lib.a
#   8 in wiced_ble_connect_timing_lib.a
#   4 in wiced_uart_raw_mode_lib.a
#   1 in dbfw_lib.a
#   7 in wiced_audio_source_lib.a
#   3 in mesh_optimized_continuous_scan_lib.a
# patch ram used: 28688 out of 64512 bytes, 44%
