# 20719B2 firmware build 199
# patch entries used: 146 out of 256 elf patches, 57%
CY_PATCH_ENTRIES_BASE=146
# additional patch entries in these libraries:
#   4 in wiced_uart_raw_mode_lib.a
#   2 in ant_lib.a
#   2 in wiced_app_watchdog_lib.a
#   1 in wiced_ble_connect_timing_lib.a
#   7 in wiced_audio_source_lib.a
#   3 in mesh_optimized_continuous_scan_lib.a
#   1 in dbfw_lib.a
# patch ram used: 28068 out of 64512 bytes, 43%
